# Generated by Django 2.1.2 on 2018-10-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_music', '0002_auto_20181001_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='fname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='lname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='nick_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
